### ISSUE TITLE
博主大大你好，可以向您要个联系方式嘛！

### ISSUE THREAD

**Issue by zhanjuex** [omigeft/Chinese-Clinical-Terminology-Standardization-Task#2]

**Comment by omigeft** [comment]
请私信来意

**Comment by zhanjuex** [comment]
想在您的基础上继续做研究可以吗，因为我正好在做cdn这块，感觉这个用处还是非常大的，想得到您的授权（不是白嫖）。

**Comment by omigeft** [comment]
可以在遵守开源协议[The Apache License 2.0](https://github.com/omigeft/Chinese-Clinical-Terminology-Standardization-Task/blob/main/LICENSE)和本项目的参考项目[shibing624/MedicalGPT](https://github.com/shibing624/MedicalGPT/tree/main)的要求的情况下自由使用。
